### ISSUE TITLE
License for this module

### ISSUE THREAD

**Issue by timothyschoen** [izzyreal/juce-raw-keyboard-input-module#3]
Hi/Hoi!

I'm looking to include this module in my project [plugdata](https://github.com/plugdata-team/plugdata), I desperately need a module for raw keyboard input!

I was wondering if you'd be willing to license this repository under a BSD, MIT or GPL license so I'll be able to include it without running the risk of getting sued!

**Comment by izzyreal** [comment]
Hey :) Yeah sure. If you want you can create a PR for it. I'm doing GPL3 on my other repos, but whatever license you think is least restrictive.

Maybe first check if this module is what you're looking for. I welcome suggestions, contributions, improvements, etc.

**Comment by timothyschoen** [comment]
I'm planning to maybe release an AAX version in the future, in which case I'm going to need clearance from all the GPL projects I've included, so if you could license it under BSD3 0-clause (or other BSD is also okay), that would be fantastic. I'm planning to include it as a submodule, I'll contribute back any of the improvements I make!

(also, despite releasing an AAX plugin, the main parts of my project will always remain open and GPL licensed. Just the AAX SDK needs to be closed source)

**Comment by izzyreal** [comment]
I'll add the license asap. In the meantime, did you make any technical assessment of the module? I just don't want you to start using something that is subpar, and there's a very high chance at least some aspects of the module are.

One thing that comes to mind is that https://github.com/izzyreal/juce-raw-keyboard-input-module/blob/main/raw_keyboard_input/src/LinuxKeyboard.cpp sets up a global keystroke reader, unbound to a specific window's message stream, which of course poses security risks. The macOS and Windows code may have similar implications.

Just know that the module is the result of doing the bare minimum to get things to work for my use case, which is not a very demanding one, nor is it commercial.

**Comment by izzyreal** [comment]
GPL3 license added a54a9438a59db40262879f64dd882051f75cf2a7

**Comment by timothyschoen** [comment]
Thanks, I'm now using this in plugdata: https://github.com/plugdata-team/plugdata/tree/develop/Libraries/raw-keyboard-input-module

We use it for the keycode object we have.

**Comment by izzyreal** [comment]
@timothyschoen Thanks for the heads-up, and great that the module is proving useful for you! You may have noticed that last week I've added key repeats to the Linux implementation. Be aware that it [uses some hardcoded values for delay and interval](https://github.com/izzyreal/juce-raw-keyboard-input-module/blob/eb10727720b954cbf6dd29784e605755c7ad0132/raw_keyboard_input/src/LinuxKeyboard.cpp#L15), since I haven't figured out how to read them from the user's config yet. It _should_ [check if key repeats are globally enabled](https://github.com/izzyreal/juce-raw-keyboard-input-module/blob/eb10727720b954cbf6dd29784e605755c7ad0132/raw_keyboard_input/src/LinuxKeyboard.cpp#L49), but I haven't tested whether this works/is respected. Moreover, I think there are ways in X11 to say "this key repeats, that key doesn't", and the module does not distinguish between such cases.
